name: flappy_bird
description: "Flappy Bird Game"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flame: ^1.17.0
  flame_audio: ^2.10.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#ADD8E6"
  image: assets/images/bird_midflap.png 
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  color: "#42a5f5"
  image_path : "assets/images/bird_midflap.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: Game
      fonts:
        - asset: assets/fonts/Game.ttf